version: 2
jobs:
  test:
    docker:
      - image: circleci/node:14-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Audit Dependencies
          command: npm run audit
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Running Integration Tests
          command: npm run integration-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
